### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [kingrpaul/eleanor-h-porter_pollyanna-grows-up#1]
- [x]  In the content.opf, the collection metadata needs to be:
`<meta id="collection-1" property="belongs-to-collection">Glad Books</meta>`
`<meta property="collection-type" refines="#collection-1">series</meta>`
`<meta property="group-position" refines="#collection-1">2</meta>`

- [x]  In chapter 8, the poem structure needs to be tweaked a little. Please move the double left quote and the endnote link into their proper `<span>` sections. See [Section 7.5](https://standardebooks.org/manual/1.3.1/single-page#7.5) in the manual for examples.

- [x]  Please replace the poem CSS you currently have with what is provided in the manual. This is also located in [Section 7.5](https://standardebooks.org/manual/1.3.1/single-page#7.5) in the manual.

- [x]  You are missing the base CSS for the dedication. See [Section 7.3](https://standardebooks.org/manual/1.3.1/7-high-level-structural-patterns#7.3) in the manual.

- [x]  Please run `se typogrify .`
